### ISSUE TITLE
Polish source cda-hd.pl change to filmtu.pl

### ISSUE THREAD

**Issue by tomasiek** [nixgates/Incursion#1]
Polish source cda-hd.pl change to filmtu.pl - you have only to change url in https://github.com/nixgates/Incursion/blob/master/script.module.incursion/lib/resources/lib/sources/pl/cdahd.py

**Comment by nixgates** [comment]
This has been addressed and an update will be available tonight. 

Thank you for your help.

**Comment by tomasiek** [comment]
You do not need to make changes - they returned to the old address cda-hd.pl.
I apologize for the false alarm
