### ISSUE TITLE
Unable to set library integration for TV, Movies library integration works.

### ISSUE THREAD

**Issue by SamBudeh** [nixgates/Incursion#10]
After setting the content type under Tools/Library/TV Folder..., the contextual menu does not show the option 'Add to Library' for folders under Incursion / TV Shows.

**Comment by nixgates** [comment]
What folder are you trying to add? You won't be able to add folders such as 'Most Popular' but you can add specific shows individually.

**Comment by Kr1ss-XD** [comment]
@SamBudeh : 

U can also add ur Trakt "Collection" (or any other personal Trakt (or IMDb) list of movies/shows) in one step.

To import the Trakt "Collection" go to _Tools_/_Library_/_Import Trakt Collection_ (or _Import Trakt TV Show Collection_).
For Collection or other lists, navigate to that list, and pick _Add to Library_ from its context menu.

As @nixgates stated above, it won't work for dynamic list from the Trakt/IMDb/TVMaze sites, but __only__for ur own personal lists on Trakt or IMDb.

**Comment by SamBudeh** [comment]
@nixgates @Kr1ss-XD I was trying to add My TV Shows / Progress. I used My Movies / Watchlist for movies.

**Comment by nixgates** [comment]
You can import the Collection and the Watchlist directories.
I also put in place a new feature in the latest update that will help in auto updating your Trakt collections to your Kodi Library. 

You can find it in the 'General' Tab of the settings page.

Closing issue.
