### ISSUE TITLE
Movie and TV Show Viewtypes cannot be different

### ISSUE THREAD

**Issue by drinfernoo** [nixgates/Incursion#11]
It seems that whatever I set the Viewtype to for either Movies or TV Shows, the other one is always the same.

Seasons and Episodes seem to work just fine.

**Comment by nixgates** [comment]
Can you identify the exact directories you are referring to? 

Do you mean something similar to: "Incursion > TV Shows > Most Popular"

**Comment by drinfernoo** [comment]
I can try and go through and see which ones specifically. It may be working now, actually ;)

**Comment by nixgates** [comment]
I'm sorry I didn't get back to you earlier about this. I found the fix a while ago and forgot to mention it to you.

There is an option that actually comes from covenant, inside Incurison > Tools > Viewtypes >  (select what section you want to save) > Click here to save view. 

That should fix your issue.
