### ISSUE TITLE
Not an issue...but a thank you :)

### ISSUE THREAD

**Issue by bjgood** [nixgates/Incursion#19]
Hey Dev,
I wanted to thank you for fixing watchcartoon_gw (now watchnixtoons) by Dandy. You've made my kids, and me, very happy. I can never thank you enough.

Count me as one of your fans.

Have a good one. :).

Thanks, again, buddy.

Bob

**Comment by nixgates** [comment]
I'm glad there's some smiles around :)

I appreciate the compliment.
