### ISSUE TITLE
WatchNixtoons is down

### ISSUE THREAD

**Issue by bjgood** [nixgates/Incursion#23]
Hey nixgates,
This evening, Feb. 26th at 7:00pm EST USA, WatchNixtoons is down. None of my cartoon links will work. It could be temporary, but the website is up. Guess I'll know more tomorrow.

Just a heads-up, dude.

Later...
Bob

**Comment by bjgood** [comment]
Sorry, dude. It was just a temporary condition. WatchNixtoons is working again.

Sorry for the fuss.

Have a good one. :).
Bob

**Comment by christophered** [comment]
then close this topic
