### ISSUE TITLE
Possible memory leak and error while "New Search"

### ISSUE THREAD

**Issue by B1naryKill3r** [nixgates/Incursion#38]
Hello!
I have Kodi on OSMC on RaspberryPI 3.
Every time I try to search for a movie/tv show error appears.

In a log i found this:

> 19:00:01.458 T:1060385536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <class 'sqlite3.ProgrammingError'>
>                                             Error Contents: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
>                                             Traceback (most recent call last):
>                                               File "/home/osmc/.kodi/addons/plugin.video.incursion/incursion.py", line 175, in <module>
>                                                 movies.movies().search_new()
>                                               File "/home/osmc/.kodi/addons/script.module.incursion/lib/resources/lib/indexers/movies.py", line 213, in search_new
>                                                 dbcur.execute("INSERT INTO movies VALUES (?,?)", (None,q))
>                                             ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
>                                             -->End of Python script error report<--
> 19:00:01.560 T:1259860736 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
> 19:00:01.711 T:1926330880 WARNING: Previous line repeats 2 times.
> 19:00:01.711 T:1926330880   ERROR: GetDirectory - Error getting plugin://plugin.video.incursion/?action=movieSearchnew
> 19:00:01.714 T:1926330880   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.incursion/?action=movieSearchnew) failed

**Comment by B1naryKill3r** [comment]
UPDATE: I realized that this error happens only when i search `Seria niefortunnych zdarzeń`, when i type `Lemony Snicket` everything works.

**Comment by nixgates** [comment]
Issue has been patched and will be released with next update.
