### ISSUE TITLE
Alluc is not able to be disabled from the "Providers Menu"

### ISSUE THREAD

**Issue by nixgates** [nixgates/Incursion#4]
It's been noted that Alluc is not within the providers menu.

This will need to be investigated and fixed if required.

**Comment by weekendsource** [comment]
add

`        <setting id="provider.allucen" type="bool" label="ALLUC" default="true" />`


into plugin.video.incursion/resources/settings.xml after allrls

**Comment by nixgates** [comment]
ALLUC has since shutdown.

Closing issue.
