### ISSUE TITLE
Cloudflare changed their challenge

### ISSUE THREAD

**Issue by Prometheusx-git** [nixgates/Incursion#40]
Hi,
Cloudflare changed their challenge, so the script.module.incursion/lib/resources/lib/modules/cfscrape.py won't work anymore.
Anorov has updated his code under https://github.com/Anorov/cloudflare-scrape.
But his version uses node.js as dependency, which isn't used in your script.
Therefore a rework of the script is needed to make it working without node.js.

**Comment by nixgates** [comment]
Thanks for letting me know, I'll adjust the cfscrape module to suit with the next update.

**Comment by nixgates** [comment]
I have a fixed version of cfscrape, will push with next update.

**Comment by nixgates** [comment]
Cfscraper has been fixed.
