### ISSUE TITLE
Block code within Control.py

### ISSUE THREAD

**Issue by HenioH** [nixgates/Incursion#46]
Hello nixgates
Very thankful for your fork and such a great job on the maintenance. I did notice there was some left over block code from the early days of when covenant was forked from exodus and tvaddons where blocking certain other addons. was wondering if you could delete this piece of code after you take a look of course. It unnecessarily blocks such apps as Metalliq, Chappa'ai, Metallik to directly play any links from incursion. I manually delete it or put a hashtag in front of it to ignore script and to allow links to play but once an update comes out it puts it back to default. It also allows the use of shortcut links to certain section of incursion within super favourites. I know alot would appreciate it. 

Location: script.module.incursion/lib/resources/lib/control.py

around line 233:     if not infoLabel('Container.PluginName') in netloc: sys.exit()

**Comment by ellite** [comment]
Why not save nixgates the trouble and create a Pull Request with those changes?
Then, if nixgates sees fit, he can just merge it.

**Comment by rene1980** [comment]
The easy way to use SuperFavourite is the following:

in the Line: 
moderator():
    netloc = [urlparse.urlparse(sys.argv[0]).netloc,..... add 'plugin.program.super.favourites']

**Comment by vitorp07** [comment]
The easiest way to remove the block-code without changing much is to change "sys.exit()" for "pass" 
at line 233;

`if not infoLabel('Container.PluginName') in netloc: sys.exit()`
to
`if not infoLabel('Container.PluginName') in netloc: pass`

**Comment by nixgates** [comment]
Moderator has been disabled in last update and is due to be completely removed in next release.

Closing Issue
