### ISSUE TITLE
mywatchseries provider needs fix

### ISSUE THREAD

**Issue by doko-desuka** [nixgates/Incursion#52]
That site behaves differently depending on the amount of seasons and episodes that a show has. When there's a lot of eps, the page only shows the first few episodes of a season plus a "load more episodes" button which does a POST request asking for more. This is detectable by looking for a span of class "load_more", its onclick attribute tells what season it's loading more episodes for.
An example of a page with these buttons: https://dwatchseries.to/serie/the_daily_show
(The javascript for the button can be seen at the bottom of the page source, search for loadMoreLinks)

The current scraper works only with pages of shows with few episodes (when all episodes are shown on the page):
https://github.com/nixgates/Incursion/blob/master/script.module.incursion/lib/resources/lib/sources/en/mywatchseries.py#L78

I can't write a PR for this right now.

**Comment by nixgates** [comment]
If you are happy to write a PR I'll be happy to merge it :)

**Comment by nixgates** [comment]
Sorry I totally misread the previous comment as "I can write a PR for this".

I will pass over this scraper and fix the issue before the next udpate.

**Comment by dokoab** [comment]
I don't know if it's any help, in a personal add-on I'm doing the POST request like this:

```
    load_more = soup.find_all('span', 'load_more')
    if load_more:
        se = int( load_more[0].a['onclick'].replace(r'javascript:loadMoreLinks(', '').replace(r')', '') )
        show_id = soup.find_all('input', id='show_id')[0]['value']
        post_data = {'show_id': show_id, 'season': se, 'order': 'orderDescendingBoth'}
        EP_BASE_URL = ep_url.split('_s%d_e' % (se))[0]
        other_eps = json.loads( post_url(BASE_URL + POST_URL, post_data).text )
        for ep_item in other_eps:
            ep_num = ep_item['episode']
            ep_url = '%s_s%d_e%s.html' % (EP_BASE_URL, se, ep_num)
            ep_airdate = ep_item['aired']

...

def post_url(url, data):
    s = session_global.SESSION
    s.headers.update({'User-Agent' : r'Mozilla/5.0 (Windows NT 6.3; rv:36.0) Gecko/20100101 Firefox/36.0'})
    r = s.post(url, data)
    if r.status_code != requests.codes.ok:
        raise Exception("Could not post to the web")
    return r
```
I'll leave this issue open, please feel free to close it as needed.
