### ISSUE TITLE
Debrid Services not appearing

### ISSUE THREAD

**Issue by inna984** [nixgates/Incursion#58]
I don't know if its just me but I noticed that no real-debrid links are showing up when searching for a movie/tv show. However, I do know that real-debrid was having service issues yesterday but it appears to be working in all my other add-ons just perfectly. I've tried to re-authorize incursion just to see if it would start showing the links and it still won't. Genesis is showing real-debrid links and so is covenant and some other addons. This is the only one that isn't working right now.

**Comment by inna984** [comment]
ok thanks. did try reinstalling kodi though and incursions still just the only addon that it doesn't work or pull links from. even if you change the option to only pull debrid links only, it'll still pull all links minus debrid.

**Comment by inna984** [comment]
nm it was an issue with resolvenow...fixed it...this case can close

**Comment by bill381** [comment]
I am not getting real-debrid links either with incursion but I am getting them with my other Addons.

**Comment by bill381** [comment]
Mine works now as well. I’m not sure what I did to make it work but it didn’t work before.
