### ISSUE TITLE
Help for adding a source

### ISSUE THREAD

**Issue by mderiano** [nixgates/Incursion#59]
Hi,

first of all, I'm not a python developper, I don't know anything about python. I'm a php developper.

I'm trying to add a french source, but as I said, I'm not a python developper and the dom parsing part is a bit complicate.

Just would like to know if someone here could agree to help me and teach me a little, so I can add more sources in the future.

Here's my begining of code

`import re
import urllib
import urlparse
import web_pdb

from resources.lib.modules import cleantitle
from resources.lib.modules import client
from resources.lib.modules import dom_parser2
from resources.lib.modules import source_utils

class source:
    def __init__(self):
        self.priority = 1
        self.language = [\'fr\']
        self.domains = [\'libertyvf.com\', \'libertyvf.net\']
        self.base_link = \'http://libertyvf.com\'
        self.search_link = \'v2/recherche/\'

    def movie(self, imdb, title, localtitle, aliases, year):
        try:
            clean_title = cleantitle.getsearch(localtitle)
            search_url = urlparse.urljoin(self.base_link, self.search_link)
            post = {'mot_search': clean_title, 'categorie': 'films'}
            r = client.request(search_url, post= post)

            r = client.parseDOM(r, 'div', {'class': 'bloc-generale'})

            web_pdb.set_trace()

            r = [(dom_parser2.parse_dom(i, 'h2', attrs={'class': 'heading'}),
                  dom_parser2.parse_dom(i, 'a', attrs={'href': re.compile('.*/annee/\d+.html')})) for i in r]

            return
        except Exception:
            return
`

As you can see, I've been able to load the libertyvf.com result page in my script. But this page is very badly done and there is no class for the "results" div. So I have to parse every "bloc-generale" div even if some are just advertising or something else. Then if this "bloc-generale" is really a result it will have an h2 with class heading and little further will have a link with the year. But when I trace the results with web_pdb it doesn't return the link with the year (even if my regex seem fine), and how can I remove the empty results ?

Thank you.

**Comment by dokoab** [comment]
I'd try using BeautifulSoup whenever possible, just to avoid it being a mistake in your regex (and it's faster too). script.module.Incursion imports it, so you can use it in your scripts.

- https://github.com/nixgates/Incursion/blob/master/script.module.incursion/lib/resources/lib/sources/en/cmovies.py#L140
- https://medium.freecodecamp.org/how-to-scrape-websites-with-python-and-beautifulsoup-5946935d93fe

Then you can use it to get all the "bloc-generale" and find the one that has the movie info: it's the bloc-generale that has a child div of class "avatar", or also a child div of class "divstreaming".
It will also have a <li> child whose .get_text() .startsWith('Date'), where you can regex capture the year of the movie

**Comment by mderiano** [comment]
BeautifulSoup helped me a lot, unfortunately there is captcha on the link and I can't find a way to pass it.

I thought it was possible because there is an option in incursion for captcha, but I can't find any other source with captcha to see how it's done.

**Comment by host505** [comment]
I think the setting on incursion refers to 'hosters' with captchas, ie the sites that actually host the video files.
And these are handled by the resolver (script.module.resolveurl).
Not sure about 'sources' with captchas.

**Comment by mderiano** [comment]
Thank you for your help, but it does'nt worked.

I will try to add other sources without captcha, but I've just started a new job and will have less time for it now.
