### ISSUE TITLE
Downloads not showing movies

### ISSUE THREAD

**Issue by designfusionjb** [nixgates/Incursion#65]
I enable downloads the setup Movies and TV locations. I restart Kodi and go to Incursion/Downloads but only TV is displayed. Movies section is missing. Tested same procedure in Covenant and Movies is displayed.

**Comment by nixgates** [comment]
As you've stated, this seems to be more on an issue that is outside of Incursion. But thank you for taking the time to raise an issue, it may help another user in the future.
