### ISSUE TITLE
problems in allucen 

### ISSUE THREAD

**Issue by krzysztof222** [nixgates/Incursion#67]
allucen sources do not appear

**Comment by ellite** [comment]
Allucen was removed.

**Comment by dokoab** [comment]
Looks like someone made a replacement.
https://www.reddit.com/r/Addons4Kodi/comments/8f641y/introducing_llucy_a_drop_in_alluc_replacement/

They say the API should be similar (drop-in).

**Comment by nixgates** [comment]
Alluc has gone offline and I don't like the idea of adding their sister site Pron as it is predominantly a porn search engine. The risk of scraping porn is to high for what should a be a family friendly addon.

I will however look into llucy, hopefully this will be a good alternative and I'll finally be able to do some quality changes to the ALLUC scraper.
