### ISSUE TITLE
Chillax Stopped Working

### ISSUE THREAD

**Issue by findmystream** [nixgates/Incursion#71]
Chillax stopped working.  It was working perfectly!!

**Comment by bjgood** [comment]
Chillax never did work for me.

**Comment by findmystream** [comment]
It worked perfect for me until this past Thursday.  Chillax has a notice on their site saying they are having issues but the videos stream on their site now so I wasn't sure if they should be working in Incursion again.  You have to have a premium membership with Chillax to have it work.

**Comment by findmystream** [comment]
I purchase a 6 month subscription because it was working so good and then it stopped.

**Comment by nixgates** [comment]
You shouldn't have needed to purchase a subscription for Chillax for it have worked in the past, the scraper worked around their premium membership requirements.

Unfortunately, Chillax has changed their login feature to include a Google Recaptcha and I can't bypass that. 

All in all, I'm sorry to say Chillax will be removed this coming update.
