### ISSUE TITLE
mywatchseries changes...easy fix

### ISSUE THREAD

**Issue by bjgood** [nixgates/Incursion#83]
Hi,
mywatchseries.to has changed its address. It was http://dwatchseries.to but now it's https://www1.swatchseries.to. I made the changes in mywatchseries.py and it's providing links again. Easy fix. nixgates, dokoab, alexnander, lorkadiscovery?

Later, dudes. :).

**Comment by dokoab** [comment]
Hi bro. You've got it! Glad to see you venturing into that.

I remember someone mentioning to use a unblocking service to find out the latest address:
https://watchseries.unblocker.cc/

(Go to unblocker.cc for the source)

**Comment by Grossdm** [comment]
It looks like the dev has abandoned this project.

BTW, I think it's better to use `http://swatchseries.to` as the URL.
