### ISSUE TITLE
Add Furk support

### ISSUE THREAD

**Issue by HypoLuxa** [nixgates/Incursion#9]
Should be similar to adding Alluc, but can be done with user/pass

Thanks

**Comment by nixgates** [comment]
Looking into Furk at the moment, I have looked through the API and checked out how it works. 

Will look at a little further in the near future.

**Comment by nixgates** [comment]
I've run a few tests with a dummy account and have emailed Furk in regards to acquiring an account for testing purposes.

**Comment by ellite** [comment]
I've developed Furkit, the Android app for Furk. Let me know if you need any help. Not that much familiar with add-on development, but familiar with Furks API.

**Comment by muzicman** [comment]
Furk is great! Here are two addons that still work but have not been updated. Info might help.
https://github.com/batchen/What-the-Furk
https://github.com/Grassboy/plugin.video.furk

**Comment by nixgates** [comment]
Experimental Furk Support is now added.

Notes:
Furk will currently appear as a non-debrid source when attempting to use it as a scraper source.
It does not currently work with any directories only direct video files.
In the Furk menu you are able to view your user files and use the metasearch for direct video files.

**Comment by nixgates** [comment]
Furk support is nearing completion, small changes need to be made to better identify files but I am now closing this issue.

Thanks for your input!
